apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmarker-config
  namespace: benchmarker
data:
  PHX_HOST: "benchmarker.example.com"
  PORT: "4000"
  PHX_SERVER: "true"
  POOL_SIZE: "20"
  UPLOAD_DIR: "/var/lib/benchmarker/uploads"
  ECTO_IPV6: "false"
