apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: benchmarker
  namespace: benchmarker
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "5g"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  ingressClassName: nginx
  tls:
    - hosts: [benchmarker.example.com]
      secretName: benchmarker-tls
  rules:
    - host: benchmarker.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: benchmarker-server
                port:
                  number: 80
