apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: benchmarker-uploads
  namespace: benchmarker
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard # gp3 on real AWS, standard on local Kind
